### PR TITLE
Allow passing "key" and "keys" to fetch

### PR DESCRIPTION
**Pull request by radicand**
This is especially useful if you have large data sets on the server, and fetch pieces here and there using {keys: [...], add: true} each time you need more, and checking your collection locally for existence before making a remote call.

For the JS, apparently my coffeescript generator is different?  Looks slightly more verbose -- let me know if I need to compile it differently.

### CODE REVIEW

**Comment by JacquesBonet** [comment]
I think "key" for fetch doesn't works because not implemented in jquery-couch.js

**Comment by radicand** [comment]
Works for me?

**Comment by JacquesBonet** [comment]
May be you right, my implementation to have key and keys parameters on the fetch was quite different of you. 

I'll try it tomorow and I'll say you.

**Comment by radicand** [comment]
Forgot to spawn this in its own branch.  Will re-open.

**Pull request closed without merging**
