### PR TITLE
Added support for startkey and endkey

### PR DESCRIPTION
**Pull request by nickkitto**
Hey Jan,
I am using your backbone-couchdb library for an application and notice it was missing support for using the startkey and endkey as allowed in the couchdb view api.
It works the same as how keys work (inside the db object inside a collection)

Here is an explanation of the logic to determine what can and can't exist in a request.
<code>
if ((coll.db != null) && (coll.db.view != null) && !(coll.db.startkey != null)) {
  delete _opts.startkey; 
  delete _opts.endkey;
}
</code>
If there is no startkey, make sure startkey and endkey are null
<code>
if ((coll.db != null) && (coll.db.view != null) && !(coll.db.endkey != null)) {
    delete _opts.endkey;
}
</code>
If there is no endkey, delete it
<code>
if ((coll.db != null) && (coll.db.view != null) && (coll.db.startkey != null)) {
    delete _opts.keys;
}
</code>
If there is a startkey, delete key.

This may or may not be your intented functionality (startkey overrides key) but this could easily be changed.

Apologies if this is in the wrong format in anyway, as this is my first submission to github.

Regards,
Nick

### CODE REVIEW

**Comment by janmonschke** [comment]
Hi, thx for your contribution!
Can you submit a patch to the original CoffeeScript source instead of the compiled JavaScript?

**Comment by nickkitto** [comment]
I added it to the coffeescript (first time writing in it, but think it is correct).
Was using the coffeescript web based tool to compile/verify it, but I'm not sure if it compiled it right. (not surrounded in function, possible other differences), so it might be best if you compile it on linux.

**Comment by nickkitto** [comment]
Pull request 34 adds these features and more, so might as well just implement that

**Comment by janmonschke** [comment]
I see, thanks for your participation! :)

**Pull request closed without merging**
