### PR TITLE
Add keys querying option

### PR DESCRIPTION
**Pull request by JacquesBonet**
This permits to write something like that :

aCollection.fetch({
    keys:[aKey],
    success:function () {
        ...
    },
    error:function () {
        ...
    }
});

### CODE REVIEW

**Comment by dvberkel** [comment]
@JacquesBonet Thanks for your idea. I used it in [notes](https://github.com/dvberkel/notes) to retrieve the documents of a specific user.

**Comment by JacquesBonet** [comment]
Happy that help you))))))))))

**Comment by janmonschke** [comment]
Hey, just stumbled upon this.
I think the functionality you are asking for already exists. 
You can add a `keys` value to each collection's db-config.
Unfortunately it is not yet documented ;)
You can find the code here: https://github.com/janmonschke/backbone-couchdb/blob/master/backbone-couchdb.coffee#L65

You use it like this:

```
var MyCollection = Backbone.Collection.extend({
    db: {
        keys: ["key1", "key2"]
    }
});
```

**Comment by janmonschke** [comment]
And now it's also documented ;)

http://janmonschke.com/projects/backbone-couchdb.html#custom_parameters

**Comment by JacquesBonet** [comment]
Hello Jan,

Doesn't understand why you say it was already implemented?

In your case you have to create a new collection each time you have new keys parameters to query. 

In my case, I keep my current collection, and I need only to do a new fetch. This follow the same behavior has limit, skip, include_docs, startkey, endkey parameters.

Far better no?

**Comment by janmonschke** [comment]
Now I see ;)
Can you create a new pull request and add it to the coffeescript file?

**Comment by JacquesBonet** [comment]
Yes with pleasure

Envoyé depuis mon mobile Orange

----- Reply message -----
De : "Jan Monschke" reply@reply.github.com
Pour : "Jacques Bonet" jacques.bonet@gmail.com
Objet : [backbone-couchdb] Add keys querying option (#39)
Date : jeu., mai 3, 2012 12:06

Now I see ;)
Can you create a new pull request and add it to the coffeescript file?

---

**Comment by JacquesBonet** [comment]
Hi Jan,

Somebody do a pull request on backbone-couchdb for keys to fetch.

Do you always want I do my pull request on the same subject?

Remark : the pull request for key doesn't works, because not implemented in
jquery-couch.js, so I think the pull request of radicand need some
adaptation.

Regards

2012/5/3 jacques.bonet@gmail.com jacques.bonet@gmail.com

> Yes with pleasure
> 
> Envoyé depuis mon mobile Orange
> 
> ----- Reply message -----
> De : "Jan Monschke" <
> reply@reply.github.com
> 
> > Pour : "Jacques Bonet" jacques.bonet@gmail.com
> > Objet : [backbone-couchdb] Add keys querying option (#39)
> > Date : jeu., mai 3, 2012 12:06
> 
> Now I see ;)
> Can you create a new pull request and add it to the coffeescript file?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/janmonschke/backbone-couchdb/pull/39#issuecomment-5484520

## 

_Jacques Bonet_
Ingenieur Software Freelance

20 rue de la mairie
79500 Saint Martin Les Melle
France

✆ +33 6 35495090
✉ jacques.bonet@gmail.com

**Pull request closed without merging**
